languageCode = "fr-fr"
title = "Seanops website"
baseurl = "http://seanops.github.io"
theme = "hugo-future-imperfect"

[params]
    # Sets the meta tag description, usually reserved for the main page
    description          = "SEANOPS static website"
    # This will appear on the top left of the navigation bar
    navbarTitle          = "Seanops"

[params.intro]
    header    = "tech notes"
    paragraph = ""
    about     = "Devops between sea and tech"

[params.postAmount]
    sidebar = 1

[[menu.main]]
    name = "Blog"
    url = "/blog"
    identifier = "fa fa-newspaper-o"
    weight = 1

[[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 3
